import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./component/footer";
import { Toaster } from "sonner";
import Provider from "./component/provider";
import { CartProvider } from "./src/context/Contextapi";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Provider>
          <CartProvider>
          <Toaster richColors position="top-right" />
          {children} <Footer/>
          </CartProvider>
        </Provider>
      </body>
    </html>
  );
}
